"""Multiscale SDF encoder with perturbation-conditioned layer modulation."""

from __future__ import annotations

import math
from typing import Iterable

import torch
from torch import nn
import torch.nn.functional as F


class ModulatedTransformerLayer(nn.Module):
    def __init__(self, hidden_dim: int, heads: int, perturb_dim: int, dropout: float = 0.0) -> None:
        super().__init__()
        self.attn = nn.MultiheadAttention(hidden_dim, heads, dropout=dropout, batch_first=True)
        self.norm1 = nn.LayerNorm(hidden_dim)
        self.norm2 = nn.LayerNorm(hidden_dim)
        self.ffn = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim * 4),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim * 4, hidden_dim),
        )
        self.modulation = nn.Linear(perturb_dim, hidden_dim * 2)

    def forward(self, tokens: torch.Tensor, perturbation: torch.Tensor) -> torch.Tensor:
        attended, _ = self.attn(tokens, tokens, tokens, need_weights=False)
        hidden = self.norm1(tokens + attended)
        gamma, beta = self.modulation(perturbation).chunk(2, dim=-1)
        hidden = hidden * (1.0 + gamma[:, None]) + beta[:, None]
        return self.norm2(hidden + self.ffn(hidden))


class MultiscaleGeometryEncoder(nn.Module):
    """Encode an airfoil SDF and normalized condition into one conditioning code.

    Patch embeddings are generated by strided convolutions. To keep attention
    tractable at full grid resolution, each scale is adaptively pooled to at
    most ``max_token_grid`` by ``max_token_grid`` tokens. This preserves the
    manuscript's multiscale interface while avoiding quadratic memory growth.
    """

    def __init__(
        self,
        patch_scales: Iterable[int] = (4, 8, 16),
        hidden_dim: int = 256,
        condition_dim: int = 512,
        layers: int = 6,
        heads: int = 8,
        max_token_grid: int = 16,
        dropout: float = 0.0,
    ) -> None:
        super().__init__()
        self.patch_scales = list(patch_scales)
        self.hidden_dim = hidden_dim
        self.max_token_grid = int(max_token_grid)
        self.patch_embeddings = nn.ModuleList(
            [nn.Conv2d(1, hidden_dim, kernel_size=scale, stride=scale) for scale in self.patch_scales]
        )
        self.scale_embeddings = nn.Parameter(torch.randn(len(self.patch_scales), hidden_dim) * 0.02)
        self.reference_condition = nn.Parameter(torch.zeros(2), requires_grad=False)
        self.reference_geometry = nn.Parameter(torch.zeros(hidden_dim))
        perturb_dim = hidden_dim
        self.perturbation_mlp = nn.Sequential(
            nn.Linear(2 + 2 + hidden_dim, hidden_dim * 2),
            nn.GELU(),
            nn.Linear(hidden_dim * 2, perturb_dim),
        )
        self.layers = nn.ModuleList(
            [ModulatedTransformerLayer(hidden_dim, heads, perturb_dim, dropout) for _ in range(layers)]
        )
        self.output = nn.Sequential(
            nn.Linear(hidden_dim + perturb_dim + hidden_dim, condition_dim),
            nn.GELU(),
            nn.Linear(condition_dim, condition_dim),
        )

    @staticmethod
    def _position_encoding(height: int, width: int, dim: int, device: torch.device, dtype: torch.dtype) -> torch.Tensor:
        y, x = torch.meshgrid(
            torch.linspace(-1.0, 1.0, height, device=device, dtype=dtype),
            torch.linspace(-1.0, 1.0, width, device=device, dtype=dtype),
            indexing="ij",
        )
        positions = torch.stack([x, y], dim=-1).reshape(-1, 2)
        quarter = max(dim // 4, 1)
        freq = torch.exp(
            torch.arange(quarter, device=device, dtype=dtype)
            * (-math.log(10000.0) / max(quarter - 1, 1))
        )
        encoded = torch.cat(
            [
                torch.sin(positions[:, :1] * freq),
                torch.cos(positions[:, :1] * freq),
                torch.sin(positions[:, 1:] * freq),
                torch.cos(positions[:, 1:] * freq),
            ],
            dim=1,
        )
        if encoded.shape[1] < dim:
            encoded = F.pad(encoded, (0, dim - encoded.shape[1]))
        return encoded[:, :dim]

    def tokenize(self, sdf: torch.Tensor) -> torch.Tensor:
        tokens = []
        for index, embed in enumerate(self.patch_embeddings):
            feature = embed(sdf)
            target_h = min(feature.shape[-2], self.max_token_grid)
            target_w = min(feature.shape[-1], self.max_token_grid)
            feature = F.adaptive_avg_pool2d(feature, (target_h, target_w))
            token = feature.flatten(2).transpose(1, 2)
            position = self._position_encoding(target_h, target_w, self.hidden_dim, sdf.device, sdf.dtype)
            token = token + position[None] + self.scale_embeddings[index][None, None]
            tokens.append(token)
        return torch.cat(tokens, dim=1)

    def forward(self, sdf: torch.Tensor, condition: torch.Tensor) -> torch.Tensor:
        tokens0 = self.tokenize(sdf)
        geometry_gap = tokens0.mean(dim=1)
        geometry_delta = geometry_gap - self.reference_geometry[None]
        condition_delta = condition - self.reference_condition[None]
        perturbation = self.perturbation_mlp(
            torch.cat([condition, condition_delta, geometry_delta], dim=-1)
        )
        tokens = tokens0
        for layer in self.layers:
            tokens = layer(tokens, perturbation)
        return self.output(torch.cat([tokens.mean(dim=1), perturbation, geometry_delta], dim=-1))
